export type Vehicle =
  | "Retail PIE"
  | "KiwiSaver"
  | "Workplace / Super"
  | "ETF"
  | "Closed";

export type Style =
  | "Core cash / MMF"
  | "Enhanced cash"
  | "Bank-deposit PIE"
  | "Cash-plus / short duration";

/** Typical cash-available settlement after a valid redemption instruction. */
export type Settlement = "T+0" | "T+1" | "T+2" | "T+3" | "Restricted" | "Closed";

export const SETTLEMENTS: Settlement[] = [
  "T+0",
  "T+1",
  "T+2",
  "T+3",
  "Restricted",
  "Closed",
];

export const SETTLEMENT_HINT: Record<Settlement, string> = {
  "T+0": "Same-day / on-call",
  "T+1": "Next business day",
  "T+2": "Two business days",
  "T+3": "Three business days",
  Restricted: "KiwiSaver withdrawal rules",
  Closed: "Existing investors only",
};

/**
 * GENIUS Act reserve-collateral analog (liquidity and duration only).
 * Duration is the portfolio weighted-average remaining maturity of named
 * holdings, scored in lib/genius.ts. Not a legal determination that a US
 * permitted payment stablecoin issuer may hold the fund.
 */
export type GeniusReserve = "Yes" | "Partial" | "No";

export const GENIUS_RESERVES: GeniusReserve[] = ["Yes", "Partial", "No"];

export const GENIUS_HINT: Record<GeniusReserve, string> = {
  Yes: "WAM ≤ 20 days; no ineligible assets",
  Partial: "WAM ≤ 93 days, or the extract is incomplete",
  No: "WAM above 93 days, or ineligible asset types",
};

export type Holding = {
  name: string;
  weight: number;
  type?: string;
};

export type AnnualReturn = {
  year: number;
  fundAfterFeesTax: number;
  categoryAverage?: number;
};

export type Fund = {
  slug: string;
  name: string;
  manager: string;
  fnd: string | null;
  vehicle: Vehicle;
  style: Style;
  pie: boolean;
  open: boolean;
  fumMillion: number | null;
  fumAsOf: string | null;
  members: number | null;
  started: string | null;
  feePercent: number | null;
  managerFee?: number | null;
  otherFee?: number | null;
  riskIndicator: 1 | 2 | 3 | null;
  return3yAfterFeesTax: number | null;
  return1yAfterFeesTax: number | null;
  return1yAfterFeesBeforeTax?: number | null;
  annualReturns: AnnualReturn[];
  mandate: string;
  benchmark: string;
  targetMix: string;
  actualMix?: string;
  liquidity: string;
  settlement: Settlement;
  minInvestment: string | null;
  distributions: string;
  holdings: Holding[];
  notes?: string;
  sources: { label: string; url: string }[];
};

export const RESEARCH_AS_OF = "2026-09-08";

export const funds: Fund[] = [
  {
    slug: "milford-cash-fund",
    name: "Milford Cash Fund",
    manager: "Milford Funds",
    fnd: "FND13445",
    vehicle: "Retail PIE",
    style: "Cash-plus / short duration",
    pie: true,
    open: true,
    fumMillion: 1070,
    fumAsOf: "2026-03-31",
    members: 2816,
    started: "2019-03-01",
    feePercent: 0.2,
    managerFee: 0.19,
    otherFee: 0.01,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.33,
    return1yAfterFeesTax: 2.19,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.19, categoryAverage: 1.96 },
      { year: 2025, fundAfterFeesTax: 3.73, categoryAverage: 3.78 },
      { year: 2024, fundAfterFeesTax: 4.07, categoryAverage: 3.39 },
      { year: 2023, fundAfterFeesTax: 2.33, categoryAverage: -0.79 },
    ],
    mandate:
      "Target a return above the New Zealand Official Cash Rate after the base fund fee but before tax. Primarily invests in New Zealand cash, short-dated debt securities and term deposits.",
    benchmark: "Official Cash Rate (OCR)",
    targetMix: "20% cash / 80% NZ fixed interest",
    actualMix: "15.4% cash, 77.4% NZ FI, 7.3% intl FI (31 Mar 2026)",
    liquidity: "Daily dealing; typical cash-fund settlement of a few business days",
    settlement: "T+2",
    minInvestment: "$1,000",
    distributions: "Accumulating (unit price compounds daily)",
    holdings: [
      { name: "Westpac 45-day wholesale notice deposit", weight: 14.19, type: "NZ FI" },
      { name: "BNZ NZD cash call account", weight: 13.65, type: "Cash" },
      { name: "Port of Tauranga CP 17/06/2026", weight: 3.73, type: "NZ FI" },
      { name: "ASB Bank 4.1% 04/05/2026", weight: 3.55, type: "NZ FI" },
      { name: "BNZ 1.884% 08/06/2026", weight: 3.42, type: "NZ FI" },
    ],
    notes:
      "Largest standalone retail cash fund in this survey. Morningstar places it in NZ OE Cash. Fact sheets also publish a KiwiSaver twin.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND13445/milford-cash-fund/" },
      { label: "Sorted Smart Investor", url: "https://www.smartinvestor.sorted.org.nz/kiwisaver-and-managed-funds/SCH10700/OFR10702/FND13445/" },
    ],
  },
  {
    slug: "booster-enhanced-cash-portfolio",
    name: "Booster Enhanced Cash Portfolio",
    manager: "Booster",
    fnd: "FND1312",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 384,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2008-02-14",
    feePercent: 0.04,
    managerFee: 0,
    otherFee: 0.04,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.08,
    return1yAfterFeesTax: 2.21,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.21, categoryAverage: 1.96 },
      { year: 2025, fundAfterFeesTax: 3.53, categoryAverage: 3.78 },
      { year: 2024, fundAfterFeesTax: 3.51, categoryAverage: 3.39 },
    ],
    mandate:
      "Invests entirely in income assets. Suited to investors looking for an on-call investment with a low level of risk who will accept relatively modest returns.",
    benchmark: "Cash / short-term bank paper (defensive income)",
    targetMix: "100% cash and cash equivalents",
    actualMix: "100% cash and cash equivalents",
    liquidity: "On-call / same-scheme dealing",
    settlement: "T+0",
    minInvestment: "Via Booster Investment Scheme",
    distributions: "Accumulating",
    holdings: [
      { name: "NZ cash (BNZ bank trust account)", weight: 10.97 },
      { name: "BNZ bank bill 28/04/2026", weight: 10.36 },
      { name: "Westpac TD 08 Jul 2026 @ 2.997%", weight: 6.32 },
      { name: "Westpac TD 23 Apr 2026 @ 3.466%", weight: 5.36 },
      { name: "ASB TD 20 Apr 2026 @ 3.570%", weight: 5.32 },
    ],
    notes: "Lowest published annual fund charge among open retail cash PIEs in this survey (0.04%).",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND1312/booster-enhanced-cash-portfolio/" },
      { label: "Sorted Smart Investor", url: "https://smartinvestor.sorted.org.nz/kiwisaver-and-managed-funds/SCH10844/OFR10852/FND1312/" },
    ],
  },
  {
    slug: "amova-nz-cash-fund",
    name: "Amova NZ Cash Fund",
    manager: "Amova (formerly Nikko AM NZ)",
    fnd: "FND383",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 384.4,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2014-06-12",
    feePercent: 0.3,
    managerFee: 0.3,
    otherFee: 0,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.58,
    return1yAfterFeesTax: 2.45,
    return1yAfterFeesBeforeTax: 3.4,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.45, categoryAverage: 1.96 },
    ],
    mandate:
      "Outperform the Bloomberg NZBond Bank Bill Index by 0.20% p.a. over a rolling three-year period before fees, expenses and taxes. Actively managed short-term deposits and bonds, with a capital-preservation objective and regular income.",
    benchmark: "Bloomberg NZBond Bank Bill Index + 0.20% p.a. (before fees)",
    targetMix: "100% cash and cash equivalents",
    actualMix: "About 74% cash / remainder short NZ fixed interest (31 Mar 2026)",
    liquidity: "Daily dealing",
    settlement: "T+2",
    minInvestment: "Via platforms and Amova scheme",
    distributions: "Income-oriented",
    holdings: [
      { name: "MUFG Bank Auckland FRN 24/11/2026", weight: 2.84 },
      { name: "Kiwibank 2.635% 05/10/2026", weight: 2.57 },
      { name: "BNZ 1.884% 08/06/2026", weight: 2.5 },
      { name: "Toyota Finance NZ FRN 30/09/2027", weight: 2.31 },
    ],
    notes:
      "Nikko AM New Zealand rebranded to Amova. Still a core institutional-quality NZ money-market sleeve and a common underlying holding (Clarity Enhanced Cash holds the wholesale twin).",
    sources: [
      { label: "Q1 2026 fund update (GoalsGetter)", url: "https://www.goalsgetter.co.nz/hubfs/Downloads/HistoricQFUs/2026/Q1_Retail/AmovaNZCashFund_Mar26.pdf" },
      { label: "Sorted Smart Investor", url: "https://www.smartinvestor.sorted.org.nz/kiwisaver-and-managed-funds/SCH10488/OFR10608/FND383/" },
    ],
  },
  {
    slug: "superlife-nz-cash-fund",
    name: "SuperLife NZ Cash Fund",
    manager: "Smartshares / SuperLife",
    fnd: "FND2407",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 246.8,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2016-10-28",
    feePercent: 0.42,
    managerFee: 0.4,
    otherFee: 0.02,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.17,
    return1yAfterFeesTax: 2.09,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.09, categoryAverage: 1.96 },
      { year: 2025, fundAfterFeesTax: 3.77, categoryAverage: 3.78 },
      { year: 2024, fundAfterFeesTax: 3.65, categoryAverage: 3.39 },
    ],
    mandate:
      "Invests in New Zealand cash, including term deposits, and is designed to outperform (before tax, fees and other expenses) the S&P/NZX Bank Bill 90-Day Index over rolling one-year periods.",
    benchmark: "S&P/NZX Bank Bill 90-Day Index",
    targetMix: "100% cash and cash equivalents",
    actualMix: "100% cash and cash equivalents",
    liquidity: "Daily dealing via SuperLife Invest",
    settlement: "T+2",
    minInvestment: "Via SuperLife / Smart",
    distributions: "Accumulating",
    holdings: [
      { name: "NZLGFA 1.50% 15/04/2026", weight: 3.31 },
      { name: "Rabobank FRN 08/12/2026", weight: 2.69 },
      { name: "Kiwibank TD 17/12/2026 3.15%", weight: 2.53 },
      { name: "Toyota Finance NZ FRN 30/09/2027", weight: 2.41 },
      { name: "BNZ 1.884% 08/06/2026", weight: 2.38 },
    ],
    notes: "Same manager sleeve as the Smart NZ Cash ETF and SuperLife KiwiSaver / Master Trust cash funds.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND2407/superlife-nz-cash-fund/" },
      { label: "SuperLife QFU 31 Mar 2026", url: "https://www.superlife.co.nz/files/LegalDocs/SLI-FundUpdates/2026-Mar/superlife%20invest%20fund%20update_nz_cash_fund.pdf" },
    ],
  },
  {
    slug: "mercer-macquarie-nz-cash-fund",
    name: "Mercer Macquarie NZ Cash Fund",
    manager: "Mercer / Macquarie",
    fnd: "FND78",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 233,
    fumAsOf: "2026-03-31",
    members: null,
    started: "1995-06-01",
    feePercent: 0.3,
    managerFee: 0.25,
    otherFee: 0.05,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.28,
    return1yAfterFeesTax: 2.17,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.17, categoryAverage: 1.96 },
      { year: 2025, fundAfterFeesTax: 3.65, categoryAverage: 3.78 },
      { year: 2024, fundAfterFeesTax: 4.03, categoryAverage: 3.39 },
    ],
    mandate:
      "Actively managed portfolio of bank bills, floating-rate notes, short-term securities and liquid deposits. Targets capital security and a gross return above the Bloomberg NZBond Bank Bill Index on a rolling 12-month basis. ESG is integrated where applicable.",
    benchmark: "Bloomberg NZBond Bank Bill Index",
    targetMix: "100% cash and cash equivalents",
    actualMix: "100% cash and cash equivalents",
    liquidity: "Daily dealing; also used as an InvestNow feeder",
    settlement: "T+2",
    minInvestment: "Via Mercer / InvestNow / platforms",
    distributions: "Accumulating",
    holdings: [
      { name: "Westpac NZ FRN 06/07/2026", weight: 6.26 },
      { name: "ASB RCD 20/05/2026", weight: 6.24 },
      { name: "Rabobank Nederland FRN 08/12/2026", weight: 5.95 },
      { name: "ASB RCD 13/08/2026", weight: 4.34 },
      { name: "NZLGFA 1.50% 15/04/2026", weight: 4.2 },
    ],
    notes: "Longest-running dedicated NZ cash fund in the survey (inception 1995). InvestNow offers a feeder (FND20531).",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND78/mercer-macquarie-nz-cash-fund/" },
    ],
  },
  {
    slug: "harbour-enhanced-cash-fund",
    name: "Harbour Enhanced Cash Fund",
    manager: "Harbour Asset Management",
    fnd: "FND15505",
    vehicle: "Retail PIE",
    style: "Enhanced cash",
    pie: true,
    open: true,
    fumMillion: 228,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2019-08-01",
    feePercent: 0.26,
    managerFee: 0.17,
    otherFee: 0.09,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.74,
    return1yAfterFeesTax: 2.74,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.74, categoryAverage: 1.96 },
      { year: 2025, fundAfterFeesTax: 4.19, categoryAverage: 3.78 },
      { year: 2024, fundAfterFeesTax: 4.3, categoryAverage: 3.39 },
    ],
    mandate:
      "Actively managed NZD money-market securities, NZ Government stock, corporate bonds and bank deposits. Designed to earn a premium over 90-day bank bills while avoiding traditional bond-fund volatility. Maximum permitted duration is 2 years. Harbour’s fact sheet objective is to outperform the S&P/NZX Bank Bills 90-Day Index by 85 bps p.a. over a rolling 3-year period.",
    benchmark: "S&P/NZX Bank Bills 90-Day Index + 85 bps (fact sheet)",
    targetMix: "45% cash / 55% NZ fixed interest",
    actualMix: "27.4% cash / 72.6% NZ FI (31 Mar 2026)",
    liquidity: "Daily; core holding of highly liquid securities for cash-flow",
    settlement: "T+2",
    minInvestment: "Via platforms (Consilium and others)",
    distributions: "Accumulating",
    holdings: [
      { name: "NZ Government Stock 15/05/2028 0.25%", weight: 13.3 },
      { name: "Kiwibank 2.635% 05/10/2026", weight: 5.32 },
      { name: "ASB 5.928% 16/11/2026", weight: 5.1 },
      { name: "BNZ 1.884% 08/06/2026", weight: 3.51 },
      { name: "Westpac deposit 3.015% 17/08/2026", weight: 3.3 },
    ],
    notes:
      "Harbour’s June 2026 fact sheet reported market value of about $260m, yield to maturity 3.06%, modified duration 0.25 years and credit duration 0.72 years. Predecessor wholesale short-duration fund dates to April 2012.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND15505/harbour-enhanced-cash-fund/" },
      { label: "Harbour fact sheet", url: "https://www.harbourasset.co.nz/assets/Fact-Sheets/Fund-fact-sheet-Enhanced-Cash.pdf" },
    ],
  },
  {
    slug: "kernel-cash-plus-fund",
    name: "Kernel Cash Plus Fund",
    manager: "Kernel Wealth",
    fnd: "FND40596",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 209,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2022-11-07",
    feePercent: 0.25,
    managerFee: 0.25,
    otherFee: 0,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.79,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Designed to invest in short-term New Zealand interest-bearing assets and other cash and cash equivalent investments. The KiwiSaver twin targets a return (before tax, fees and expenses) that closely matches the Bloomberg NZBond Bank Bill Index.",
    benchmark: "Bloomberg NZBond Bank Bill Index",
    targetMix: "100% cash and cash equivalents",
    actualMix: "92.1% cash / 7.9% NZ FI (31 Mar 2026)",
    liquidity: "Daily via Kernel",
    settlement: "T+1",
    minInvestment: "$1",
    distributions: "Accumulating",
    holdings: [
      { name: "Bank of China deposit", weight: 0 },
      { name: "Kiwibank FRNs and commercial paper", weight: 0 },
      { name: "Transpower NZ FRN 31/07/2028", weight: 0 },
    ],
    notes:
      "Kernel also runs a KiwiSaver Cash Plus sleeve (FND40600) with $17.6m and 490 members at 30 June 2026 — a separate scheme, same strategy family.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND40596/kernel-cash-plus-fund/" },
    ],
  },
  {
    slug: "nz-funds-cash-portfolio",
    name: "NZ Funds Cash Portfolio",
    manager: "NZ Funds",
    fnd: "FND1605",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 145,
    fumAsOf: "2025-12-31",
    members: null,
    started: "2008-02-28",
    feePercent: 0.41,
    managerFee: 0.3,
    otherFee: 0.11,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.03,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Provide a source of capital. Anticipated to mainly own and trade cash and cash equivalents over the minimum suggested timeframe.",
    benchmark: "Cash / cash-equivalent peer group",
    targetMix: "Cash and cash equivalents",
    liquidity: "Daily via NZ Funds",
    settlement: "T+2",
    minInvestment: "Via NZ Funds",
    distributions: "Accumulating",
    holdings: [],
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND1605/nz-funds-cash-portfolio/" },
    ],
  },
  {
    slug: "clarity-enhanced-cash-pie",
    name: "Clarity Enhanced Cash PIE",
    manager: "Clarity Funds",
    fnd: "FND50928",
    vehicle: "Retail PIE",
    style: "Enhanced cash",
    pie: true,
    open: true,
    fumMillion: 138,
    fumAsOf: "2026-01-31",
    members: null,
    started: "2024-06-11",
    feePercent: 0.25,
    managerFee: 0.18,
    otherFee: 0.08,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Provide regular income in excess of bank deposits while preserving capital. Invests, directly or through other managed funds, in a diversified portfolio of cash, cash equivalents and NZ fixed interest, including yield-enhancing assets such as mortgage-backed securities and credit funds.",
    benchmark: "Bloomberg NZBond Bank Bill Index",
    targetMix: "50% cash / 50% NZ fixed interest (SIPO target)",
    actualMix: "About 92% cash / 8% NZ FI (31 Mar 2026)",
    liquidity:
      "Same-day processing if received by 1pm; cash typically available within three further business days. No buy/sell spread.",
    settlement: "T+3",
    minInvestment: "Via Clarity / advisers",
    distributions: "Quarterly",
    holdings: [
      { name: "Amova Wholesale NZ Cash Fund", weight: 81.1 },
      { name: "NZMS First Mortgage Securities", weight: 7.3 },
      { name: "Bank of China (NZ)", weight: 7.3 },
      { name: "Bank of New Zealand", weight: 4.3 },
    ],
    notes:
      "January 2026 fact sheet showed $138m FUM and a 3.24% PIR (max 28%) yield versus 1.01% for an average bank cash PIE. Mindful Money later reported $125m at 31 March 2026. Portfolio manager: Andrew Kelleher.",
    sources: [
      { label: "January 2026 fact sheet", url: "https://clarityfunds.co.nz/sites/default/files/documents/Enhanced%20Cash%20PIE%20Factsheet%20January%202026_0.pdf" },
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND50928/clarity-enhanced-cash-pie/" },
    ],
  },
  {
    slug: "bnz-private-wealth-cash-fund",
    name: "BNZ Private Wealth Series Cash Fund",
    manager: "BNZ Investment Services",
    fnd: "FND3629",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 132,
    fumAsOf: "2025-12-31",
    members: null,
    started: "2017-03-02",
    feePercent: 0.27,
    managerFee: 0.27,
    otherFee: 0,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.37,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Invests in income assets including New Zealand short-term cash securities and cash equivalents. Aims for stable short-term returns and a gross return in excess of its benchmark index.",
    benchmark: "Cash / bank-bill style index (BNZ PW series)",
    targetMix: "100% cash and cash equivalents",
    actualMix: "100% cash and cash equivalents",
    liquidity: "Via BNZ Private Wealth",
    settlement: "T+2",
    minInvestment: "BNZ Private Wealth relationship",
    distributions: "Accumulating",
    holdings: [],
    sources: [
      { label: "Mindful Money fund card", url: "https://www.mindfulmoney.nz/managed/FND3629/bnz-private-wealth-series-cash-fund/" },
    ],
  },
  {
    slug: "octagon-enhanced-cash-fund",
    name: "Octagon Enhanced Cash Fund",
    manager: "Octagon (Forsyth Barr)",
    fnd: "FND44200",
    vehicle: "Retail PIE",
    style: "Enhanced cash",
    pie: true,
    open: true,
    fumMillion: 125,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2023-06-07",
    feePercent: 0.36,
    managerFee: 0.36,
    otherFee: 0,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Invests in cash, cash equivalents and short-term New Zealand debt securities. Aims to achieve returns (before fees, taxes and other expenses) greater than the Official Cash Rate over a rolling 12-month period.",
    benchmark: "Official Cash Rate (OCR)",
    targetMix: "65% cash / 35% NZ fixed interest",
    actualMix: "57.7% cash / 42.3% NZ FI (31 Mar 2026)",
    liquidity: "Daily via Octagon / Forsyth Barr",
    settlement: "T+2",
    minInvestment: "Via Octagon / platforms",
    distributions: "Accumulating",
    holdings: [],
    notes: "Successor / rebranded line to the former QuayStreet cash capability inside the Forsyth Barr group.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND44200/octagon-enhanced-cash-fund/" },
    ],
  },
  {
    slug: "wedge-savings-fund",
    name: "Wedge Savings Fund",
    manager: "Wedge Management",
    fnd: null,
    vehicle: "Retail PIE",
    style: "Cash-plus / short duration",
    pie: true,
    open: true,
    fumMillion: 114.5,
    fumAsOf: "2026-06-30",
    members: null,
    started: "2025-04-28",
    feePercent: null,
    riskIndicator: 2,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Actively managed portfolios of cash, cash equivalents and fixed interest via underlying Wedge funds. Aims for an annualised return above New Zealand bank on-call savings rates while keeping capital stable and providing ready access. MoneyHub has cited a marketed fixed-style rate around 3.15% p.a. after fees, before tax — confirm on the current PDS.",
    benchmark: "NZ bank on-call savings rates",
    targetMix: "Cash, cash equivalents and fixed interest",
    liquidity: "Ready access (savings-style PIE)",
    settlement: "T+0",
    minInvestment: "Via Wedge",
    distributions: "Marketed as a savings-style return",
    holdings: [
      { name: "Kiwibank 02/04/2027", weight: 9.6 },
      { name: "Bank of America NA Australia 30/10/2026", weight: 5.38 },
      { name: "United Overseas Bank Sydney 28/02/2028", weight: 4.28 },
      { name: "UBS AG Australia 24/11/2026", weight: 4.02 },
      { name: "Infratil 15/12/2026", weight: 3.69 },
    ],
    notes:
      "Younger product (April 2025). Holdings include Australian and Canadian bank paper as well as NZ names — more credit and tenor diversity than a strict NZ bank-bill MMF.",
    sources: [
      { label: "QFU 30 June 2026 (Sorted)", url: "https://www.smartinvestor.sorted.org.nz/disclose-document/a0c370d19d277416/Wedge-Savings-Fund-Quarterly-Fund-Update---30-June-2026.pdf" },
      { label: "MoneyHub cash funds guide", url: "https://www.moneyhub.co.nz/cash-funds.html" },
    ],
  },
  {
    slug: "sharesies-pie-save",
    name: "Sharesies PIE Save Fund",
    manager: "Sharesies Investment Management",
    fnd: null,
    vehicle: "Retail PIE",
    style: "Bank-deposit PIE",
    pie: true,
    open: true,
    fumMillion: 112.9,
    fumAsOf: "2026-06-30",
    members: null,
    started: "2024-11-25",
    feePercent: 0,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: 1.77,
    return1yAfterFeesBeforeTax: 2.26,
    annualReturns: [],
    mandate:
      "Invest wholly in dollar deposits at AA-rated registered NZ-based banks. Conservative, stable short-term return with easy access. Targets the Official Cash Rate before fund charges and tax.",
    benchmark: "Official Cash Rate (OCR)",
    targetMix: "100% NZ bank deposits (AA-)",
    actualMix: "100% ANZ NZD cash call account (30 Jun 2026 QFU)",
    liquidity: "Easy access via Sharesies; monthly unit distributions",
    settlement: "T+0",
    minInvestment: "Via Sharesies (no traditional minimum)",
    distributions: "Monthly, by issuing new units",
    holdings: [{ name: "NZD cash call account (ANZ Bank)", weight: 100, type: "AA bank deposit" }],
    notes:
      "No separate advertised management fee; Sharesies earns the spread between the investor rate and the rate received from the bank. June 2026 QFU: 2.26% after charges before tax vs 2.55% market index.",
    sources: [
      { label: "QFU June 2026", url: "https://assets.ctfassets.net/eg3voq9njjf7/2AWr1TglwnnhkuPWkmgxP/8aee133c8a02597fcfc6a9be7316d731/Sharesies_Pie_Save__June_2026_.pdf" },
      { label: "PDS 5 Dec 2024", url: "https://assets.ctfassets.net/eg3voq9njjf7/1TPFKz0Ro8bfehSIczv8Xz/c033675c036af33caadb076d6651395e/Product_Disclosure_Statement__PDS__-_Sharesies_PIE_Save__5_December_2024_.pdf" },
    ],
  },
  {
    slug: "simplicity-nz-cash-fund",
    name: "Simplicity NZ Cash Fund",
    manager: "Simplicity",
    fnd: "FND43090",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 91.5,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2023-04-28",
    feePercent: 0.12,
    managerFee: 0.12,
    otherFee: 0,
    riskIndicator: 2,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Provides exposure to debt securities. Return is expected to be stable with lower volatility than Simplicity’s other funds. Renamed from the Defensive Investment Fund in 2024; manager’s basic fee cut from 0.25% to 0.10% (QFU cites 0.12% total).",
    benchmark: "Bloomberg NZBond Bank Bill Index",
    targetMix: "100% income / cash and cash equivalents",
    actualMix: "100% cash and cash equivalents",
    liquidity: "Daily; $1 minimum",
    settlement: "T+1",
    minInvestment: "$1",
    distributions: "Accumulating",
    holdings: [
      { name: "Cash at bank", weight: 10.57 },
      { name: "Kiwibank FRN 13 Jun 2028", weight: 8.27 },
      { name: "Westpac FRN 6 Jul 2026", weight: 8.01 },
      { name: "Kiwibank FRN 15 Mar 2028", weight: 6.68 },
      { name: "Housing NZ 2.247% 5 Oct 2026", weight: 5.32 },
    ],
    notes: "Lowest-fee open standalone cash PIE among diversified managers in this survey after Booster’s 0.04% administration-only charge.",
    sources: [
      { label: "Simplicity QFU 31 Mar 2026", url: "https://simplicity.kiwi/assets/Uploads/Simplicity-NZ-Cash-Fund-update-31-March-2026.pdf" },
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND43090/simplicity-nz-cash-fund/" },
    ],
  },
  {
    slug: "smart-nz-cash-etf",
    name: "Smart NZ Cash ETF (NZC)",
    manager: "Smartshares",
    fnd: "FND1104",
    vehicle: "ETF",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 36.8,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2015-11-12",
    feePercent: 0.2,
    managerFee: 0.2,
    otherFee: 0,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.41,
    return1yAfterFeesTax: 2.28,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.28, categoryAverage: 1.96 },
      { year: 2025, fundAfterFeesTax: 3.91, categoryAverage: 3.78 },
      { year: 2024, fundAfterFeesTax: 4.05, categoryAverage: 3.39 },
    ],
    mandate:
      "Provide a return (before tax, fees and other expenses) that outperforms the S&P/NZX Bank Bills 90-Day Total Return Index over rolling one-year periods.",
    benchmark: "S&P/NZX Bank Bills 90-Day Total Return Index",
    targetMix: "100% cash and cash equivalents",
    actualMix: "100% cash and cash equivalents",
    liquidity: "NZX-listed; brokerage and bid/ask apply",
    settlement: "T+2",
    minInvestment: "1 share via NZX / brokers",
    distributions: "ETF distribution policy (check current fact sheet)",
    holdings: [
      { name: "NZLGFA 1.50% 15/04/2026", weight: 3.17 },
      { name: "Bank of China deposit", weight: 2.67 },
      { name: "Rabobank FRN 08/12/2026", weight: 2.57 },
      { name: "Kiwibank TD 17/12/2026 3.15%", weight: 2.42 },
    ],
    notes: "Only NZX-listed dedicated NZ cash ETF. Morningstar category NZ OE Cash. NAV and market price can diverge slightly.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND1104/smart-nz-cash-etf/" },
      { label: "Morningstar NZC", url: "https://www.morningstar.com/etfs/xnze/nzc/performance" },
    ],
  },
  {
    slug: "mas-cash-fund",
    name: "MAS Cash Fund",
    manager: "Medical Funds Management",
    fnd: "FND47119",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 30.2,
    fumAsOf: "2025-12-31",
    members: null,
    started: "2024-01-31",
    feePercent: 0.24,
    managerFee: 0.24,
    otherFee: 0,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Invests in a range of cash and cash equivalent investments. Aims for stable short-term returns and is suitable for investors who need very low volatility. MoneyHub has highlighted it as a strong recent performer with daily liquidity.",
    benchmark: "Cash / cash-equivalent peer group",
    targetMix: "100% cash and cash equivalents",
    actualMix: "100% cash and cash equivalents",
    liquidity: "Daily; no term-deposit break fees",
    settlement: "T+1",
    minInvestment: "Via MAS",
    distributions: "Accumulating",
    holdings: [],
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND47119/mas-cash-fund/" },
      { label: "MoneyHub cash funds guide", url: "https://www.moneyhub.co.nz/cash-funds.html" },
    ],
  },
  {
    slug: "amp-new-zealand-cash-fund",
    name: "AMP New Zealand Cash Fund",
    manager: "AMP Wealth Management NZ",
    fnd: "FND757",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 29.1,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2011-03-10",
    feePercent: 0.5,
    managerFee: 0.31,
    otherFee: 0.19,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.0,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Single-sector fund investing primarily in cash and short-term deposits. Aims for modest, stable returns with very low investment risk and no significant short-term movements in value.",
    benchmark: "Cash / short-term deposit peer group",
    targetMix: "100% cash and cash equivalents",
    actualMix: "100% cash and cash equivalents",
    liquidity: "Daily via AMP Investment Trust",
    settlement: "T+2",
    minInvestment: "Via AMP",
    distributions: "Accumulating",
    holdings: [
      { name: "BNZ maturing 05 Jan 2026", weight: 9.92 },
      { name: "ASB maturing 09 Feb 2026", weight: 6.05 },
      { name: "BNZ maturing 19 Jan 2026", weight: 4.96 },
      { name: "Westpac maturing 03 Feb 2026", weight: 4.4 },
    ],
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND757/amp-new-zealand-cash-fund/" },
    ],
  },
  {
    slug: "tempo-cash-fund",
    name: "Tempo Cash Fund",
    manager: "Tempo / Octagon",
    fnd: "FND45298",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 26.5,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2023-08-16",
    feePercent: 1.1,
    managerFee: 1.1,
    otherFee: 0,
    riskIndicator: 1,
    return3yAfterFeesTax: 2.64,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Aims for positive long-term returns by investing in an underlying fund (or funds) that hold cash, cash equivalents and short-term New Zealand fixed interest. Portfolio management sits with Octagon.",
    benchmark: "Underlying Octagon cash sleeve",
    targetMix: "Cash, cash equivalents and short NZ FI via underlying fund",
    liquidity: "Via Tempo",
    settlement: "T+2",
    minInvestment: "Via Tempo",
    distributions: "Accumulating",
    holdings: [],
    notes: "Highest published annual fund charge in the open retail cash set. Fee drag is material versus a 3% cash yield.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND45298/tempo-cash-fund/" },
    ],
  },
  {
    slug: "fisher-funds-cashplus-fund",
    name: "Fisher Funds Cashplus Fund",
    manager: "Fisher Funds",
    fnd: "FND1060",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 12.6,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2008-04-30",
    feePercent: 0.83,
    managerFee: 0.5,
    otherFee: 0.33,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.16,
    return1yAfterFeesTax: 2.06,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.06, categoryAverage: 1.96 },
      { year: 2025, fundAfterFeesTax: 3.63, categoryAverage: 3.78 },
      { year: 2024, fundAfterFeesTax: 3.81, categoryAverage: 3.39 },
    ],
    mandate:
      "Stable returns and reduced potential of capital loss over the short to medium term by investing in New Zealand cash and short-term fixed interest assets.",
    benchmark: "NZ cash / short-term FI",
    targetMix: "100% cash and cash equivalents (duration < 6 months in underlying)",
    actualMix: "100% cash classification; holdings include short NZ FI",
    liquidity: "Daily via Fisher Funds",
    settlement: "T+2",
    minInvestment: "Via Fisher Funds",
    distributions: "Accumulating",
    holdings: [
      { name: "ANZ current accounts", weight: 9.66 },
      { name: "BNZ FRN 23/11/2026", weight: 5.32 },
      { name: "NZLGFA 4.50% 15/04/2027", weight: 4.99 },
      { name: "Westpac FRN 06/07/2026", weight: 3.6 },
    ],
    notes: "Same underlying credit book as Fisher’s much larger KiwiSaver Cash Fund ($463m) and the new Premium Cash Fund.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND1060/fisher-funds-cashplus-fund/" },
    ],
  },
  {
    slug: "generate-cashplus-managed-fund",
    name: "Generate CashPlus Managed Fund",
    manager: "Generate",
    fnd: "FND56148",
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 3.92,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2025-04-30",
    feePercent: 0.46,
    managerFee: 0.43,
    otherFee: 0.03,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Stable return over the very short term. Actively managed portfolio predominantly of income assets with maturity of less than one year. Volatility is likely to be very low; a negative return is unlikely but still possible.",
    benchmark: "Short-term income / <1 year maturity",
    targetMix: "Income assets < 1 year",
    liquidity: "Daily via Generate",
    settlement: "T+2",
    minInvestment: "Via Generate",
    distributions: "Accumulating",
    holdings: [{ name: "BNZ Jun 2026 bonds", weight: 0 }],
    notes: "Retail twin of Generate’s larger KiwiSaver CashPlus Fund ($96.8m). Very new and still small.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND56148/generate-cashplus-managed-fund/" },
    ],
  },
  {
    slug: "mercer-flexisaver-cash-fund",
    name: "Mercer FlexiSaver Cash Fund",
    manager: "Mercer",
    fnd: "FND39",
    vehicle: "Workplace / Super",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 4.02,
    fumAsOf: "2025-12-31",
    members: null,
    started: "2015-10-09",
    feePercent: 0.46,
    managerFee: 0.28,
    otherFee: 0.18,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.27,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate: "Workplace FlexiSaver cash option; same defensive cash mandate family as Mercer KiwiSaver and Defence Force cash.",
    benchmark: "Bloomberg NZBond Bank Bill / Mercer cash composite",
    targetMix: "100% cash and cash equivalents",
    liquidity: "Via Mercer FlexiSaver",
    settlement: "T+2",
    minInvestment: "Scheme membership",
    distributions: "Accumulating",
    holdings: [],
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND39/mercer-flexisaver-cash-fund/" },
    ],
  },
  {
    slug: "amp-select-cash-fund",
    name: "AMP Select Cash Fund",
    manager: "AMP Wealth Management NZ",
    fnd: "FND779",
    vehicle: "Closed",
    style: "Core cash / MMF",
    pie: true,
    open: false,
    fumMillion: 1.42,
    fumAsOf: "2026-03-31",
    members: null,
    started: "2004-11-16",
    feePercent: 0.8,
    managerFee: 0.66,
    otherFee: 0.14,
    riskIndicator: 1,
    return3yAfterFeesTax: 2.41,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Single-sector cash and short-term deposits. Modest, stable returns with very low risk. Closed to new investors.",
    benchmark: "Cash / short-term deposits",
    targetMix: "100% cash and cash equivalents",
    liquidity: "Existing investors only",
    settlement: "Closed",
    minInvestment: "Closed",
    distributions: "Accumulating",
    holdings: [],
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/managed/FND779/amp-select-cash-fund/" },
    ],
  },
  {
    slug: "lifetime-cash-fund",
    name: "Lifetime Cash Fund",
    manager: "Lifetime Asset Management",
    fnd: "FND51095",
    vehicle: "Workplace / Super",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 0.154,
    fumAsOf: "2026-03-31",
    members: null,
    started: null,
    feePercent: 0.65,
    riskIndicator: 2,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Single-sector cash fund seeking to track the S&P/NZX Bank Bills 90-Day Index by investing 100% in the Fisher Institutional New Zealand Cash Fund.",
    benchmark: "S&P/NZX Bank Bills 90-Day Index",
    targetMix: "100% Fisher Institutional NZ Cash Fund",
    actualMix: "98.47% Fisher Institutional NZ Cash; 1.53% cash at bank",
    liquidity: "Via Lifetime Superannuation Master Trust",
    settlement: "T+2",
    minInvestment: "$1,000",
    distributions: "None (accumulating)",
    holdings: [{ name: "Fisher Institutional New Zealand Cash Fund", weight: 98.47 }],
    notes: "Feeder, not an independent money-market book. Very small FUM.",
    sources: [
      { label: "Lifetime product page", url: "https://www.lifetimeinvestments.co.nz/investments/superannuation-master-trust/smt-fund-options/lifetime-cash-fund/" },
      { label: "Sorted Smart Investor", url: "https://www.smartinvestor.sorted.org.nz/kiwisaver-and-managed-funds/SCH13081/OFR13082/FND51095/" },
    ],
  },
  {
    slug: "fisher-funds-premium-cash-fund",
    name: "Fisher Funds Premium Cash Fund",
    manager: "Fisher Funds",
    fnd: null,
    vehicle: "Retail PIE",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 0.25,
    fumAsOf: "2026-03-31",
    members: 13,
    started: "2026-03-10",
    feePercent: 0.4,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Stable returns and reduced potential of capital loss by investing in New Zealand cash and short-term fixed interest. Invests in the same underlying Fisher cash book as Cashplus / KiwiSaver Cash.",
    benchmark: "NZ cash / short-term FI",
    targetMix: "100% cash and cash equivalents",
    liquidity: "Daily via Fisher Premium series",
    settlement: "T+2",
    minInvestment: "Via Fisher Premium",
    distributions: "Accumulating",
    holdings: [
      { name: "ANZ current accounts", weight: 9.55 },
      { name: "BNZ FRN 23/11/2026", weight: 5.33 },
      { name: "NZLGFA 4.50% 15/04/2027", weight: 5.0 },
    ],
    notes: "Brand-new share class (10 March 2026); FUM is not yet meaningful.",
    sources: [
      { label: "Fisher QFU 31 Mar 2026", url: "https://assets.fisherfunds.co.nz/premium-cash-fund-update-march-2026" },
    ],
  },
  {
    slug: "anz-kiwisaver-cash-fund",
    name: "ANZ KiwiSaver Scheme Cash Fund",
    manager: "ANZ New Zealand Investments",
    fnd: "FND2189",
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 1340,
    fumAsOf: "2026-03-31",
    members: 48163,
    started: "2008-08-12",
    feePercent: 0.22,
    managerFee: 0.19,
    otherFee: 0.03,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.43,
    return1yAfterFeesTax: 2.35,
    return1yAfterFeesBeforeTax: 3.09,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.35, categoryAverage: 2.08 },
      { year: 2025, fundAfterFeesTax: 3.83, categoryAverage: 3.81 },
      { year: 2024, fundAfterFeesTax: 4.13, categoryAverage: 3.51 },
    ],
    mandate:
      "Invests in cash and cash equivalents issued by NZ and Australian registered banks, governments, corporations or local authorities. Aims for lower but stable short-term returns after the fund charge and before tax. The scheme uses the ANZ Wholesale Cash Fund as the working portfolio.",
    benchmark: "S&P/NZX Call Rate Deposit Index (current market index)",
    targetMix: "100% cash and cash equivalents",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "KiwiSaver membership",
    distributions: "Accumulating",
    holdings: [
      { name: "Westpac NZ FRN 06/07/2026", weight: 4.82 },
      { name: "Westpac TD 04/08/2026 2.995%", weight: 4.09 },
      { name: "Westpac RCD 01/04/2026", weight: 3.96 },
      { name: "Rabobank Nederland NZ FRN 05/04/2027", weight: 3.76 },
    ],
    notes:
      "Largest dedicated cash pool in this survey. ANZ also publishes 30 Jun 2026 performance: 0.74% (3m), 3.09% (1y), 4.61% p.a. (3y), 3.75% p.a. (5y), 2.78% p.a. (10y) after fees before tax. Separate OneAnswer and Default KiwiSaver cash sleeves exist.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/kiwisaver/FND2189/anz-kiwisaver-cash-fund/" },
      { label: "ANZ performance page", url: "https://www.anz.co.nz/personal/kiwisaver/compare-funds/performance-fees/anz-kiwisaver-scheme-cash-fund/" },
    ],
  },
  {
    slug: "asb-kiwisaver-nz-cash-fund",
    name: "ASB KiwiSaver NZ Cash Fund",
    manager: "ASB Group Investments",
    fnd: "FND528",
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 921,
    fumAsOf: "2026-03-31",
    members: 37006,
    started: "2007-10-02",
    feePercent: 0.35,
    managerFee: 0.35,
    otherFee: 0,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Exposure to investment-grade short-term deposits and fixed-interest investments with New Zealand registered banks. Target mix 100% income assets. Cost-effective management; fewer expected negative years than other ASB KiwiSaver funds.",
    benchmark: "NZ bank short-term deposits / cash",
    targetMix: "100% income assets (cash and equivalents)",
    actualMix: "100% cash and cash equivalents",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "KiwiSaver membership",
    distributions: "Accumulating",
    holdings: [
      { name: "Westpac deposit account", weight: 41.4 },
      { name: "ASB RCD 18/09/2026", weight: 9.75 },
      { name: "BNZ deposit account", weight: 8.54 },
      { name: "Rabobank Nederland NZ FRN 20/02/2029", weight: 6.91 },
      { name: "MUFG RCD 24/09/2026", weight: 5.35 },
    ],
    notes: "Very concentrated in major-bank deposits and RCDs — a classic bank-bill MMF, not an enhanced-credit book.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/kiwisaver/FND528/asb-kiwisaver-nz-cash-fund/" },
    ],
  },
  {
    slug: "westpac-kiwisaver-cash-fund",
    name: "Westpac KiwiSaver Cash Fund",
    manager: "BT Funds Management (NZ)",
    fnd: "FND339",
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 710,
    fumAsOf: "2026-03-31",
    members: 36883,
    started: "2007-10-01",
    feePercent: 0.25,
    managerFee: 0.25,
    otherFee: 0,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.54,
    return1yAfterFeesTax: 2.45,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.45, categoryAverage: 2.08 },
      { year: 2025, fundAfterFeesTax: 4.01, categoryAverage: 3.81 },
      { year: 2024, fundAfterFeesTax: 4.18, categoryAverage: 3.51 },
    ],
    mandate:
      "Stable returns over the short term. Invests in short-term income assets such as bank deposits, floating-rate notes and money-market securities. Expected to be the lowest-volatility fund in the Westpac KiwiSaver Scheme.",
    benchmark: "Short-term money-market / bank bills",
    targetMix: "100% short-term income assets",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "KiwiSaver membership",
    distributions: "Accumulating",
    holdings: [
      { name: "Bank of China call account", weight: 4.8 },
      { name: "Westpac FRN 06/07/2026", weight: 1.67 },
      { name: "Westpac 45-day notice deposit", weight: 1.56 },
    ],
    notes: "December 2025 QFU showed $666m; March 2026 Mindful Money figure is $710m.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/kiwisaver/FND339/westpac-kiwisaver-cash-fund/" },
      { label: "Westpac QFU 31 Dec 2025", url: "https://assets.dam.westpac.co.nz/is/content/wnzl/dist/kiwisaver-investments-and-managed-funds/kiwisaver-and-managed-funds/westpac-kiwisaver-scheme/Westpac-KiwiSaver-Scheme_Cash-Fund_report_31Dec25.pdf" },
    ],
  },
  {
    slug: "fisher-funds-kiwisaver-cash-fund",
    name: "Fisher Funds KiwiSaver Plan Cash Fund",
    manager: "Fisher Funds",
    fnd: "FND550",
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 463.2,
    fumAsOf: "2026-03-31",
    members: 21706,
    started: "2012-09-12",
    feePercent: 0.45,
    managerFee: 0.36,
    otherFee: 0.09,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.56,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Stable returns and reduced potential of capital loss over the short to medium term by investing in cash and New Zealand short-term fixed interest assets. Average duration of the underlying book is under six months.",
    benchmark: "NZ cash / short-term FI",
    targetMix: "100% cash and cash equivalents",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "KiwiSaver membership",
    distributions: "Accumulating",
    holdings: [
      { name: "ANZ current accounts", weight: 8.55 },
      { name: "BNZ FRN 23/11/2026", weight: 5.33 },
      { name: "NZLGFA 4.50% 15/04/2027", weight: 5.0 },
      { name: "Westpac FRN 06/07/2026", weight: 3.61 },
    ],
    sources: [
      { label: "Fisher QFU 31 Mar 2026", url: "https://assets.fisherfunds.co.nz/kiwisaver-plan-cash-fund-update-march-2026" },
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/kiwisaver/FND550/fisher-funds-kiwisaver-plan-cash-fund/" },
    ],
  },
  {
    slug: "bnz-kiwisaver-cash-fund",
    name: "BNZ KiwiSaver Cash Fund",
    manager: "BNZ Investment Services",
    fnd: "FND514",
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 365,
    fumAsOf: "2026-03-31",
    members: 16316,
    started: "2013-02-11",
    feePercent: 0.3,
    managerFee: 0.3,
    otherFee: 0,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Invests in income assets including New Zealand short-term cash securities and cash equivalents. Aims for stable short-term returns.",
    benchmark: "NZ short-term cash securities",
    targetMix: "100% income / cash equivalents",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "KiwiSaver membership",
    distributions: "Accumulating",
    holdings: [
      { name: "Westpac New Zealand", weight: 0 },
      { name: "BNZ RDA 185-day OCR +50 bps", weight: 5.06 },
      { name: "ASB RCDs", weight: 0 },
    ],
    notes: "30 June 2026 QFU: $357.9m and 16,042 investors.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/kiwisaver/FND514/bnz-kiwisaver-cash-fund/" },
      { label: "QFU 30 Jun 2026", url: "https://www.smartinvestor.sorted.org.nz/disclose-document/fe33ef6e67d7e02f/2026-06-30-BNZ-Kiwi-Saver-Cash-Fund.pdf" },
    ],
  },
  {
    slug: "milford-kiwisaver-cash-fund",
    name: "Milford KiwiSaver Cash Fund",
    manager: "Milford Funds",
    fnd: "FND17982",
    vehicle: "KiwiSaver",
    style: "Cash-plus / short duration",
    pie: true,
    open: true,
    fumMillion: 148,
    fumAsOf: "2025-09-30",
    members: 2803,
    started: "2020-03-27",
    feePercent: 0.2,
    managerFee: 0.18,
    otherFee: 0.02,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Target a return above the Official Cash Rate after the base fund fee but before tax. Primarily invests in New Zealand cash, short-dated debt securities and term deposits — same process as the retail Milford Cash Fund.",
    benchmark: "Official Cash Rate (OCR)",
    targetMix: "NZ cash, short-dated debt and term deposits",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "KiwiSaver membership",
    distributions: "Accumulating",
    holdings: [
      { name: "Westpac 45-day wholesale notice deposit", weight: 17.13 },
      { name: "Port of Tauranga commercial paper", weight: 3.1 },
    ],
    notes: "January 2026 monthly fact sheet is the latest manager commentary; FUM figure above is the September 2025 QFU.",
    sources: [
      { label: "Mindful Money fund card", url: "https://www.mindfulmoney.nz/kiwisaver/FND17982/milford-kiwisaver-cash-fund/" },
      { label: "Milford monthly fact sheet", url: "https://milfordasset.com/funds-performance/kiwisaver-cash-fund/monthly-fact-sheets/latest" },
    ],
  },
  {
    slug: "amp-kiwisaver-cash-fund",
    name: "AMP KiwiSaver Cash Fund",
    manager: "AMP Wealth Management NZ",
    fnd: "FND130",
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 114,
    fumAsOf: "2026-03-31",
    members: 2891,
    started: "2007-10-01",
    feePercent: 0.57,
    managerFee: 0.51,
    otherFee: 0.06,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: 1.84,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 1.84, categoryAverage: 2.08 },
      { year: 2025, fundAfterFeesTax: 3.38, categoryAverage: 3.81 },
      { year: 2024, fundAfterFeesTax: 3.68, categoryAverage: 3.51 },
    ],
    mandate:
      "Single-sector cash and short-term deposits. Modest, stable returns with very low investment risk.",
    benchmark: "Cash / short-term deposits",
    targetMix: "100% cash and cash equivalents",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "KiwiSaver membership",
    distributions: "Accumulating",
    holdings: [],
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/kiwisaver/FND130/amp-kiwisaver-cash-fund/" },
    ],
  },
  {
    slug: "generate-kiwisaver-cashplus-fund",
    name: "Generate KiwiSaver CashPlus Fund",
    manager: "Generate",
    fnd: null,
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 96.8,
    fumAsOf: "2025-06-30",
    members: 2784,
    started: "2022-05-16",
    feePercent: null,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Stable return over the very short term. Entirely income assets with maturity of less than one year. Useful if you plan to withdraw KiwiSaver within 12 months. Renamed from the Defensive Fund on 30 April 2025.",
    benchmark: "Short-term income / <1 year",
    targetMix: "100% income assets < 1 year",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "KiwiSaver membership",
    distributions: "Accumulating",
    holdings: [
      { name: "Westpac Feb 2026 bonds", weight: 7.79 },
      { name: "Auckland Airport Aug 2025 NZCP", weight: 7.68 },
      { name: "Contact Energy Aug 2025 NZCP", weight: 6.35 },
    ],
    sources: [
      { label: "Generate CashPlus fund update", url: "https://ap-southeast-2.graphassets.com/AKCbhBjCsTzKiieKkNfvxz/cmdmc7dvey9hc072pjfhvhiqx" },
    ],
  },
  {
    slug: "amp-nzrt-cash-fund",
    name: "AMP Cash Fund (NZRT workplace)",
    manager: "AMP Wealth Management NZ",
    fnd: null,
    vehicle: "Workplace / Super",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 78.9,
    fumAsOf: "2026-06-30",
    members: 1169,
    started: "2007-10-01",
    feePercent: null,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Single-sector cash and short-term deposits. Modest, stable returns with very low investment risk. Underlying manager support from BlackRock after AMP Capital / Macquarie exited (from 12 July 2021).",
    benchmark: "Cash / short-term deposits",
    targetMix: "100% cash and cash equivalents",
    liquidity: "Via AMP NZ Retirement Trust",
    settlement: "T+2",
    minInvestment: "Workplace scheme membership",
    distributions: "Accumulating",
    holdings: [
      { name: "ASB maturing 10 Aug 2026", weight: 5.51 },
      { name: "BNZ maturing 06 Jul 2026", weight: 4.52 },
      { name: "BNZ maturing 20 Jul 2026", weight: 4.52 },
    ],
    sources: [
      { label: "AMP NZRT QFU 30 Jun 2026", url: "https://www.amp.co.nz/content/dam/ampnz/documents/investments/NZRT/quarterly-fund-updates/2026-jun/AMP-NZRT-QFU-AMP-Cash-Fund-2026-June.pdf" },
    ],
  },
  {
    slug: "superlife-kiwisaver-nz-cash-fund",
    name: "SuperLife KiwiSaver NZ Cash Fund",
    manager: "Smartshares / SuperLife",
    fnd: "FND2465",
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 74.6,
    fumAsOf: "2026-03-31",
    members: 3169,
    started: "2007-10-08",
    feePercent: 0.52,
    managerFee: 0.5,
    otherFee: 0.02,
    riskIndicator: 1,
    return3yAfterFeesTax: 3.13,
    return1yAfterFeesTax: 2.02,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.02, categoryAverage: 2.08 },
      { year: 2025, fundAfterFeesTax: 3.69, categoryAverage: 3.81 },
      { year: 2024, fundAfterFeesTax: 3.7, categoryAverage: 3.51 },
    ],
    mandate:
      "Invests in New Zealand cash including term deposits. Designed to outperform the S&P/NZX Bank Bill 90-Day Index over rolling one-year periods before tax, fees and other expenses.",
    benchmark: "S&P/NZX Bank Bill 90-Day Index",
    targetMix: "100% cash and cash equivalents",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "KiwiSaver membership",
    distributions: "Accumulating",
    holdings: [],
    notes: "Related SuperLife Superannuation Master Trust NZ Cash Fund held $56.5m at 31 March 2026.",
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/kiwisaver/FND2465/superlife-kiwisaver-nz-cash-fund/" },
    ],
  },
  {
    slug: "superlife-smt-nz-cash-fund",
    name: "SuperLife Master Trust NZ Cash Fund",
    manager: "Smartshares / SuperLife",
    fnd: null,
    vehicle: "Workplace / Super",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 56.5,
    fumAsOf: "2026-03-31",
    members: 1297,
    started: "2000-08-01",
    feePercent: null,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Invests in New Zealand cash and is designed to outperform (before tax, fees and other expenses) the S&P/NZX Bank Bills 90-Day Total Return Index over rolling one-year periods.",
    benchmark: "S&P/NZX Bank Bills 90-Day Total Return Index",
    targetMix: "100% cash and cash equivalents",
    liquidity: "Via SuperLife Superannuation Master Trust",
    settlement: "T+2",
    minInvestment: "Scheme membership",
    distributions: "Accumulating",
    holdings: [
      { name: "NZLGFA 1.50% 15/04/2026", weight: 3.31 },
      { name: "Rabobank FRN 08/12/2026", weight: 2.68 },
    ],
    sources: [
      { label: "SuperLife SMT QFU 31 Mar 2026", url: "https://www.superlife.co.nz/files/LegalDocs/MT-FundUpdates/2026-Mar/superlife%20superannuation%20master%20trust%20fund%20update_superlife_superannuation_master_trust_nz_cash_fund.pdf" },
    ],
  },
  {
    slug: "anz-default-kiwisaver-cash-fund",
    name: "ANZ Default KiwiSaver Cash Fund",
    manager: "ANZ New Zealand Investments",
    fnd: null,
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 39.2,
    fumAsOf: "2025-06-30",
    members: 834,
    started: "2007-11-15",
    feePercent: null,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Invests in cash and cash equivalents that may include NZ-registered banks, the NZ Government, corporates, local authorities or non-NZ governments. Aims for lower but stable short-term returns after the fund charge and before tax.",
    benchmark: "S&P/NZX Call Rate Deposit Index",
    targetMix: "100% cash and cash equivalents",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "Default KiwiSaver allocation",
    distributions: "Accumulating",
    holdings: [],
    notes: "Separate from the main ANZ KiwiSaver Cash Fund. FUM figure is 30 June 2025.",
    sources: [
      { label: "ANZ Default KS QFU 30 Jun 2025", url: "https://www.anz.co.nz/content/dam/anzconz/documents/personal/investments-kiwisaver/ANZ-default-KS-disclosures/2025/ANZDKS-FU-300625-Cash.pdf" },
    ],
  },
  {
    slug: "mercer-kiwisaver-cash-fund",
    name: "Mercer KiwiSaver Cash Fund",
    manager: "Mercer",
    fnd: "FND11",
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 35.7,
    fumAsOf: "2026-03-31",
    members: 1204,
    started: "2007-10-01",
    feePercent: 0.32,
    managerFee: 0.28,
    otherFee: 0.04,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: 2.16,
    annualReturns: [
      { year: 2026, fundAfterFeesTax: 2.16, categoryAverage: 2.08 },
      { year: 2025, fundAfterFeesTax: 3.7, categoryAverage: 3.81 },
      { year: 2024, fundAfterFeesTax: 3.94, categoryAverage: 3.51 },
    ],
    mandate: "KiwiSaver cash option in the Mercer Macquarie NZ cash family — bank bills, FRNs and short deposits.",
    benchmark: "Bloomberg NZBond Bank Bill Index",
    targetMix: "100% cash and cash equivalents",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "KiwiSaver membership",
    distributions: "Accumulating",
    holdings: [
      { name: "ASB 1.646% 04/05/2026", weight: 6.03 },
      { name: "NZLGFA 1.50% 15/04/2026", weight: 4.42 },
    ],
    sources: [
      { label: "Mindful Money fund card", url: "https://mindfulmoney.nz/kiwisaver/FND11/mercer-kiwisaver-cash-fund/" },
    ],
  },
  {
    slug: "kernel-kiwisaver-cash-plus-fund",
    name: "Kernel KiwiSaver Cash Plus Fund",
    manager: "Kernel Wealth",
    fnd: "FND40600",
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 17.6,
    fumAsOf: "2026-06-30",
    members: 490,
    started: "2022-11-07",
    feePercent: 0.25,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: 2.48,
    return1yAfterFeesBeforeTax: 3.46,
    annualReturns: [],
    mandate:
      "Provide a return (before tax, fees and expenses) that closely matches the Bloomberg NZBond Bank Bill Index. Short-term NZ interest-bearing assets and cash equivalents.",
    benchmark: "Bloomberg NZBond Bank Bill Index",
    targetMix: "100% cash and cash equivalents",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "$1",
    distributions: "Accumulating",
    holdings: [],
    sources: [
      { label: "QFU 30 Jun 2026", url: "https://www.smartinvestor.sorted.org.nz/disclose-document/30bf25335364e7a7/Cash-Plus-FU-KS----Kiwi-Saver-Update---Jun-2026.pdf" },
    ],
  },
  {
    slug: "summer-new-zealand-cash",
    name: "Summer New Zealand Cash",
    manager: "Forsyth Barr / Summer",
    fnd: null,
    vehicle: "KiwiSaver",
    style: "Core cash / MMF",
    pie: true,
    open: true,
    fumMillion: 5.07,
    fumAsOf: "2026-03-31",
    members: 201,
    started: null,
    feePercent: 0.5,
    riskIndicator: 1,
    return3yAfterFeesTax: null,
    return1yAfterFeesTax: null,
    annualReturns: [],
    mandate:
      "Invests in cash, cash equivalents and short-term New Zealand debt. Aims to provide returns (before fees, taxes and other expenses) above the Official Cash Rate over a rolling 12-month period. Managed in the Octagon / Forsyth Barr cash process.",
    benchmark: "Official Cash Rate (OCR)",
    targetMix: "Cash, cash equivalents and short NZ debt",
    liquidity: "KiwiSaver restricted withdrawals",
    settlement: "Restricted",
    minInvestment: "Summer KiwiSaver membership",
    distributions: "Accumulating",
    holdings: [],
    notes: "ManagedFundsNZ has also cited a 0.62% annual charge from an earlier QFU — use the latest PDS. Five-year average annual return 2.41% to 31 March 2026.",
    sources: [
      { label: "FundCompare overview", url: "https://fundcompare.co.nz/funds/summer/summer-new-zealand-cash" },
      { label: "ManagedFundsNZ comparison", url: "https://managedfunds.nz/compare/simplicity-nz-cash-vs-summer-new-zealand-cash/" },
    ],
  },
];

export function getFund(slug: string) {
  return funds.find((fund) => fund.slug === slug);
}

export function disclosedFum(fund: Fund) {
  return fund.fumMillion ?? 0;
}

export const marketStats = (() => {
  const withFum = funds.filter((fund) => fund.fumMillion !== null);
  const totalFum = withFum.reduce((sum, fund) => sum + (fund.fumMillion ?? 0), 0);
  const retail = funds.filter((fund) => fund.vehicle === "Retail PIE" || fund.vehicle === "ETF");
  const kiwi = funds.filter((fund) => fund.vehicle === "KiwiSaver");
  const fees = funds.filter((fund) => fund.feePercent !== null).map((fund) => fund.feePercent as number);
  const returns = funds.filter((fund) => fund.return3yAfterFeesTax !== null);
  return {
    fundCount: funds.length,
    totalFum,
    retailCount: retail.length,
    kiwiCount: kiwi.length,
    medianFee: [...fees].sort((a, b) => a - b)[Math.floor(fees.length / 2)],
    minFee: Math.min(...fees),
    maxFee: Math.max(...fees),
    returnCount: returns.length,
    largest: [...withFum].sort((a, b) => (b.fumMillion ?? 0) - (a.fumMillion ?? 0))[0],
  };
})();
